baseurl = "https://justinbagley.rbind.io/"
languageCode = "en-us"
title = "blog"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/justincbagley"
    #weight = 4
    #pre = "<i class='fa fa-github'></i>"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/justincbagley"
    #weight = 4
    #pre = "<i class='fa fa-twitter'></i>"
[[menu.main]]
    name = "ResearchGate"
    url = "https://www.researchgate.net/profile/Justin_Bagley2"
[[menu.main]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/justin-c-bagley-2a8a0523"
    #weight = 4
    #pre = "<i class='fa fa-linkedin'></i>"

[params]
    description = "Justin Bagley's blog."
    disqusURL = "https://justinbagley.rbind.io"
    fullURL = "https://justinbagley.rbind.io"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

    [params.logo]
    url = "jselfie_logo.png"
    width = 50
    height = 50
    alt = "Logo"

    [params.footer]
    <p align="left"><script>
  (function() {
    var cx = '001889442856820716750:0-utetvkkfu';
    var gcse = document.createElement('script');
    gcse.type = 'text/javascript';
    gcse.async = true;
    gcse.src = 'https://cse.google.com/cse.js?cx=' + cx;
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(gcse, s);
  })();
</script>
<gcse:search></gcse:search>
</p>
